# Generated by Django 4.2.5 on 2023-09-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_lesson_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoproduct',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='accesstoproduct',
            name='can_view',
        ),
    ]
